### PR TITLE
remove now-unused rubocop-packs dependency

### PR DESCRIPTION
**Pull request by technicalpickles**
Testing this theory: https://github.com/rubyatscale/packs/issues/105

### CODE REVIEW

**Comment by technicalpickles** [comment]
This passes, so maybe a downstream use of it needs this around 🤔

**Comment by alexevanczuk** [comment]
We don't need `rubocop-packs` here ever since e70fde70fb7f6c1ce475009d3adca231e76e3414, but I forgot to remove it then! Could you also remove the RBI and the dependency listed in the gemspec?

**Comment by technicalpickles** [comment]
@alexevanczuk done!

**Comment by mbutsko** [comment]
Any update here?

**Review by ngan — APPROVED** [review]

**Comment by alexevanczuk** [comment]
Thanks @technicalpickles ! If you would bump the version and merge that it'll auto release in case users want to pick it up. We're still working on my authentication to the rubyatscale repo so I can't do that yet.

**Comment by technicalpickles** [comment]
done! https://github.com/rubyatscale/packs/pull/113

**Comment by Dukesiver** [comment]
thanks guys

**Pull request merged**
